import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "fs";
import { join, dirname, relative } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Path to the Obsidian vault plugin folder (auto-deploy on build)
// Set PLUGIN_DIR in your .env or shell environment
const VAULT_PLUGIN_DIR = process.env.PLUGIN_DIR || "";

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins,
    ],
    format: "cjs",
    target: "es2022",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    plugins: [
        {
            // Resolve "node:xyz" imports → mark them external (Electron provides them)
            name: "node-builtins",
            setup(build) {
                build.onResolve({ filter: /^node:/ }, (args) => ({
                    path: args.path,
                    external: true,
                }));
            }
        },
        {
            // Embed TypeScript source into the bundle for core self-modification (Phase 4).
            // Only active for production builds. Source files are base64-encoded and injected
            // as a global constant `EMBEDDED_SOURCE` that EmbeddedSourceManager reads at runtime.
            name: "embed-source",
            setup(build) {
                if (!prod) return; // Only embed source in production builds

                build.onEnd((result) => {
                    if (result.errors.length > 0) return; // Skip on build errors

                    try {
                        const srcDir = join(__dirname, "src");
                        const files = {};

                        function walkDir(dir) {
                            const entries = readdirSync(dir);
                            for (const entry of entries) {
                                const fullPath = join(dir, entry);
                                const stat = statSync(fullPath);
                                if (stat.isDirectory()) {
                                    // Skip test directories and node_modules
                                    if (entry === "node_modules" || entry === "__tests__" || entry === "test") continue;
                                    walkDir(fullPath);
                                } else if (entry.endsWith(".ts") || entry.endsWith(".tsx")) {
                                    const relPath = "src/" + relative(srcDir, fullPath).replace(/\\/g, "/");
                                    const content = readFileSync(fullPath, "utf-8");
                                    // Base64-encode to avoid escaping issues
                                    files[relPath] = Buffer.from(content).toString("base64");
                                }
                            }
                        }
                        walkDir(srcDir);

                        const pkg = JSON.parse(readFileSync(join(__dirname, "package.json"), "utf-8"));
                        const embedded = {
                            version: pkg.version || "0.0.0",
                            files,
                            buildConfig: {
                                format: "cjs",
                                target: "es2022",
                                external: [
                                    "obsidian", "electron",
                                    "@codemirror/autocomplete", "@codemirror/collab",
                                    "@codemirror/commands", "@codemirror/language",
                                    "@codemirror/lint", "@codemirror/search",
                                    "@codemirror/state", "@codemirror/view",
                                    "@lezer/common", "@lezer/highlight", "@lezer/lr",
                                ],
                            },
                        };

                        // Read the generated main.js and prepend the embedded source constant
                        const outfile = "main.js";
                        if (existsSync(outfile)) {
                            const mainJs = readFileSync(outfile, "utf-8");
                            const injection = `\nvar EMBEDDED_SOURCE = ${JSON.stringify(embedded)};\n`;
                            // Insert after the banner comment
                            const bannerEnd = mainJs.indexOf("*/");
                            if (bannerEnd !== -1) {
                                const patched = mainJs.slice(0, bannerEnd + 2) + injection + mainJs.slice(bannerEnd + 2);
                                writeFileSync(outfile, patched);
                            } else {
                                writeFileSync(outfile, injection + mainJs);
                            }

                            const fileCount = Object.keys(files).length;
                            const sizeKB = Math.round(JSON.stringify(embedded).length / 1024);
                            console.log(`[embed-source] Embedded ${fileCount} source files (~${sizeKB}KB)`);
                        }
                    } catch (e) {
                        console.warn("[embed-source] Failed to embed source:", e.message);
                    }
                });
            }
        },
        {
            name: "vault-deploy",
            setup(build) {
                build.onEnd(() => {
                    if (existsSync(VAULT_PLUGIN_DIR)) {
                        try {
                            copyFileSync("main.js", `${VAULT_PLUGIN_DIR}/main.js`);
                            copyFileSync("styles.css", `${VAULT_PLUGIN_DIR}/styles.css`);
                            const logoSrc = join(__dirname, "src/assets/logo.png");
                            if (existsSync(logoSrc)) {
                                copyFileSync(logoSrc, `${VAULT_PLUGIN_DIR}/logo.png`);
                            }
                            if (existsSync("sandbox-worker.js")) {
                                copyFileSync("sandbox-worker.js", `${VAULT_PLUGIN_DIR}/sandbox-worker.js`);
                            }
                            // Copy bundled skills to plugin skills directory
                            const bundledSkillsDir = join(__dirname, "bundled-skills");
                            if (existsSync(bundledSkillsDir)) {
                                const skillDirs = readdirSync(bundledSkillsDir);
                                for (const skillDir of skillDirs) {
                                    const srcDir = join(bundledSkillsDir, skillDir);
                                    if (!statSync(srcDir).isDirectory()) continue;
                                    const destDir = `${VAULT_PLUGIN_DIR}/skills/${skillDir}`;
                                    if (!existsSync(destDir)) mkdirSync(destDir, { recursive: true });
                                    const files = readdirSync(srcDir);
                                    for (const file of files) {
                                        copyFileSync(join(srcDir, file), join(destDir, file));
                                    }
                                }
                                console.log(`[vault-deploy] Copied ${skillDirs.length} bundled skill(s)`);
                            }
                            console.log(`[vault-deploy] → ${VAULT_PLUGIN_DIR}`);
                        } catch (e) {
                            console.warn("[vault-deploy] Copy failed:", e.message);
                        }
                    }
                });
            }
        }
    ],
});

// Sandbox worker — separate OS process (ADR-021)
const workerContext = await esbuild.context({
    entryPoints: ["src/core/sandbox/sandbox-worker.ts"],
    bundle: true,
    external: [],        // Standalone Node.js, no externals needed
    platform: "node",
    format: "cjs",
    target: "es2022",
    outfile: "sandbox-worker.js",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
});

if (prod) {
    // Worker first — vault-deploy (main's onEnd) copies sandbox-worker.js
    await workerContext.rebuild();
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
    await workerContext.watch();
}
